### ISSUE TITLE
Can't dowload the the kitti format of dataset .

### ISSUE THREAD

**Issue by Ircon** [azinke/coloradar#1]
click the link.
![image](https://github.com/azinke/coloradar/assets/11171522/fbe66279-1833-423f-954c-289d53d111d0)
 It is 403.
![image](https://github.com/azinke/coloradar/assets/11171522/2275f577-ef28-4f4e-a2e2-6b09a059b1df)

Would do you fix the problem?
Thanks!!!

**Comment by YLRK** [comment]
Maybe you can use a VPN to open google Drive, or contact me, I have uploaded this data set to Baidunetdisk, If you still need it.

**Comment by azinke** [comment]
There is a valid link on the dataset's website already. I'm thus closing this issue
